version: '3.8'

services:
  host:
    build:
      context: ./host
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - mfe-network

  micro:
    build:
      context: ./micro
      dockerfile: Dockerfile
    ports:
      - "4201:80"
    networks:
      - mfe-network

networks:
  mfe-network:
    driver: bridge 